<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <NoXamlPreprocessor>True</NoXamlPreprocessor>
    <OpenSilverType>7</OpenSilverType>
    <PublishTrimmed>true</PublishTrimmed>
    <WasmEnableSIMD>false</WasmEnableSIMD>
    <!--<RunAOTCompilation Condition="'$(IsSecondPass)'=='True'">true</RunAOTCompilation>-->
    <OutputPath>bin/$(Configuration)_cs</OutputPath>
    <IntermediateOutputPath>obj/$(Configuration)_cs</IntermediateOutputPath>
    <DefineTrace>true</DefineTrace>
    <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
    <WasmEnableWebcil>false</WasmEnableWebcil>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
    <PublishIISAssets>true</PublishIISAssets>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\index_WithBlazor.html" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenSilver.WebAssembly" Version="[$(OpenSilverVersion)]" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.16" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.16" PrivateAssets="all" />
  </ItemGroup>

	
	
  <ItemGroup>
    <ProjectReference Include="..\src\OpenSilver.Samples.Showcase.csproj" />
  </ItemGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="mscorlib" />
    <TrimmableAssembly Include="OpenSilver.Animations" />
    <TrimmableAssembly Include="OpenSilver.Controls.Data" />
    <TrimmableAssembly Include="OpenSilver.Controls.Data.Toolkit" />
    <TrimmableAssembly Include="OpenSilver.Controls.Theming.Toolkit" />
    <TrimmableAssembly Include="OpenSilver.ControlsKit.FastControls" />
    <TrimmableAssembly Include="OpenSilver.Expression.Effects" />
    <TrimmableAssembly Include="OpenSilver.Interactivity" />
    <TrimmableAssembly Include="OpenSilver.Data" />
  </ItemGroup>

  <ItemGroup>
    <ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
  </ItemGroup>

</Project>
