<Project>
  <PropertyGroup>
    <OpenSilverVersion Condition=" '$(OpenSilverVersion)' == '' ">3.4.0-preview-2025-12-15-190948-c76a3631</OpenSilverVersion>
    <OpenSilverBlazorVersion Condition=" '$(OpenSilverBlazorVersion)' == '' ">3.4.0-preview-2025-12-16-110429-ad048bf5</OpenSilverBlazorVersion>
    <OpenSilverModernThemeVersion Condition=" '$(OpenSilverModernThemeVersion)' == '' ">3.3.0</OpenSilverModernThemeVersion>
    <OpenSilverControlsKitVersion Condition=" '$(OpenSilverControlsKitVersion)' == '' ">3.4.0-preview-2025-11-21-110012-fa5e693</OpenSilverControlsKitVersion>
  </PropertyGroup>
</Project>