<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDefaultItems>false</EnableDefaultItems>
    <DefineSilverlight>true</DefineSilverlight>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Samples\Controls.xaml.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenSilver" Version="[$(OpenSilverVersion)]" />
    <PackageReference Include="Xaml3D" Version="0.0.1-preview-2025-11-20-070317-8ba65293" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="Samples\Controls.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

</Project>
