'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System.Runtime.Serialization

Namespace Global.ServiceReference1


    <DebuggerStepThroughAttribute()>
    <CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")>
    <DataContractAttribute(Name:="ToDoItem", [Namespace]:="http://tempuri.org/")>
    Partial Public Class ToDoItem
        Inherits Object

        Private IdField As String

        Private OwnerIdField As String

        Private DescriptionField As String

        <DataMemberAttribute(IsRequired:=True, EmitDefaultValue:=False)>
        Public Property Id As String
            Get
                Return IdField
            End Get
            Set(ByVal value As String)
                IdField = value
            End Set
        End Property

        <DataMemberAttribute(IsRequired:=True, EmitDefaultValue:=False)>
        Public Property OwnerId As String
            Get
                Return OwnerIdField
            End Get
            Set(ByVal value As String)
                OwnerIdField = value
            End Set
        End Property

        <DataMemberAttribute(EmitDefaultValue:=False, Order:=2)>
        Public Property Description As String
            Get
                Return DescriptionField
            End Get
            Set(ByVal value As String)
                DescriptionField = value
            End Set
        End Property
    End Class

    <CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")>
    <ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.IService1")>
    Public Interface IService1

        <ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetToDos", ReplyAction:="http://tempuri.org/IService1/GetToDosResponse")>
        Function GetToDosAsync(ByVal request As GetToDosRequest) As Task(Of GetToDosResponse)

        <ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/AddOrUpdateToDo", ReplyAction:="http://tempuri.org/IService1/AddOrUpdateToDoResponse")>
        Function AddOrUpdateToDoAsync(ByVal request As AddOrUpdateToDoRequest) As Task(Of AddOrUpdateToDoResponse)

        <ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/DeleteToDo", ReplyAction:="http://tempuri.org/IService1/DeleteToDoResponse")>
        Function DeleteToDoAsync(ByVal request As DeleteToDoRequest) As Task(Of DeleteToDoResponse)
    End Interface

    <DebuggerStepThroughAttribute()>
    <CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")>
    <ComponentModel.EditorBrowsableAttribute(ComponentModel.EditorBrowsableState.Advanced)>
    <ServiceModel.MessageContractAttribute(IsWrapped:=False)>
    Partial Public Class GetToDosRequest

        <ServiceModel.MessageBodyMemberAttribute(Name:="GetToDos", [Namespace]:="http://tempuri.org/", Order:=0)>
        Public Body As GetToDosRequestBody

        Public Sub New()
        End Sub

        Public Sub New(ByVal Body As GetToDosRequestBody)
            Me.Body = Body
        End Sub
    End Class

    <DebuggerStepThroughAttribute()>
    <CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")>
    <ComponentModel.EditorBrowsableAttribute(ComponentModel.EditorBrowsableState.Advanced)>
    <DataContractAttribute([Namespace]:="http://tempuri.org/")>
    Partial Public Class GetToDosRequestBody

        <DataMemberAttribute(EmitDefaultValue:=False, Order:=0)>
        Public ownerId As String

        Public Sub New()
        End Sub

        Public Sub New(ByVal ownerId As String)
            Me.ownerId = ownerId
        End Sub
    End Class

    <DebuggerStepThroughAttribute()>
    <CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")>
    <ComponentModel.EditorBrowsableAttribute(ComponentModel.EditorBrowsableState.Advanced)>
    <ServiceModel.MessageContractAttribute(IsWrapped:=False)>
    Partial Public Class GetToDosResponse

        <ServiceModel.MessageBodyMemberAttribute(Name:="GetToDosResponse", [Namespace]:="http://tempuri.org/", Order:=0)>
        Public Body As GetToDosResponseBody

        Public Sub New()
        End Sub

        Public Sub New(ByVal Body As GetToDosResponseBody)
            Me.Body = Body
        End Sub
    End Class

    <DebuggerStepThroughAttribute()>
    <CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")>
    <ComponentModel.EditorBrowsableAttribute(ComponentModel.EditorBrowsableState.Advanced)>
    <DataContractAttribute([Namespace]:="http://tempuri.org/")>
    Partial Public Class GetToDosResponseBody

        <DataMemberAttribute(EmitDefaultValue:=False, Order:=0)>
        Public GetToDosResult As ToDoItem()

        Public Sub New()
        End Sub

        Public Sub New(ByVal GetToDosResult As ToDoItem())
            Me.GetToDosResult = GetToDosResult
        End Sub
    End Class

    <DebuggerStepThroughAttribute()>
    <CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")>
    <ComponentModel.EditorBrowsableAttribute(ComponentModel.EditorBrowsableState.Advanced)>
    <ServiceModel.MessageContractAttribute(IsWrapped:=False)>
    Partial Public Class AddOrUpdateToDoRequest

        <ServiceModel.MessageBodyMemberAttribute(Name:="AddOrUpdateToDo", [Namespace]:="http://tempuri.org/", Order:=0)>
        Public Body As AddOrUpdateToDoRequestBody

        Public Sub New()
        End Sub

        Public Sub New(ByVal Body As AddOrUpdateToDoRequestBody)
            Me.Body = Body
        End Sub
    End Class

    <DebuggerStepThroughAttribute()>
    <CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")>
    <ComponentModel.EditorBrowsableAttribute(ComponentModel.EditorBrowsableState.Advanced)>
    <DataContractAttribute([Namespace]:="http://tempuri.org/")>
    Partial Public Class AddOrUpdateToDoRequestBody

        <DataMemberAttribute(EmitDefaultValue:=False, Order:=0)>
        Public toDoItem As ToDoItem

        Public Sub New()
        End Sub

        Public Sub New(ByVal toDoItem As ToDoItem)
            Me.toDoItem = toDoItem
        End Sub
    End Class

    <DebuggerStepThroughAttribute()>
    <CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")>
    <ComponentModel.EditorBrowsableAttribute(ComponentModel.EditorBrowsableState.Advanced)>
    <ServiceModel.MessageContractAttribute(IsWrapped:=False)>
    Partial Public Class AddOrUpdateToDoResponse

        <ServiceModel.MessageBodyMemberAttribute(Name:="AddOrUpdateToDoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>
        Public Body As AddOrUpdateToDoResponseBody

        Public Sub New()
        End Sub

        Public Sub New(ByVal Body As AddOrUpdateToDoResponseBody)
            Me.Body = Body
        End Sub
    End Class

    <DebuggerStepThroughAttribute()>
    <CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")>
    <ComponentModel.EditorBrowsableAttribute(ComponentModel.EditorBrowsableState.Advanced)>
    <DataContractAttribute()>
    Partial Public Class AddOrUpdateToDoResponseBody

        Public Sub New()
        End Sub
    End Class

    <DebuggerStepThroughAttribute()>
    <CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")>
    <ComponentModel.EditorBrowsableAttribute(ComponentModel.EditorBrowsableState.Advanced)>
    <ServiceModel.MessageContractAttribute(IsWrapped:=False)>
    Partial Public Class DeleteToDoRequest

        <ServiceModel.MessageBodyMemberAttribute(Name:="DeleteToDo", [Namespace]:="http://tempuri.org/", Order:=0)>
        Public Body As DeleteToDoRequestBody

        Public Sub New()
        End Sub

        Public Sub New(ByVal Body As DeleteToDoRequestBody)
            Me.Body = Body
        End Sub
    End Class

    <DebuggerStepThroughAttribute()>
    <CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")>
    <ComponentModel.EditorBrowsableAttribute(ComponentModel.EditorBrowsableState.Advanced)>
    <DataContractAttribute([Namespace]:="http://tempuri.org/")>
    Partial Public Class DeleteToDoRequestBody

        <DataMemberAttribute(EmitDefaultValue:=False, Order:=0)>
        Public toDoItem As ToDoItem

        Public Sub New()
        End Sub

        Public Sub New(ByVal toDoItem As ToDoItem)
            Me.toDoItem = toDoItem
        End Sub
    End Class

    <DebuggerStepThroughAttribute()>
    <CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")>
    <ComponentModel.EditorBrowsableAttribute(ComponentModel.EditorBrowsableState.Advanced)>
    <ServiceModel.MessageContractAttribute(IsWrapped:=False)>
    Partial Public Class DeleteToDoResponse

        <ServiceModel.MessageBodyMemberAttribute(Name:="DeleteToDoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>
        Public Body As DeleteToDoResponseBody

        Public Sub New()
        End Sub

        Public Sub New(ByVal Body As DeleteToDoResponseBody)
            Me.Body = Body
        End Sub
    End Class

    <DebuggerStepThroughAttribute()>
    <CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")>
    <ComponentModel.EditorBrowsableAttribute(ComponentModel.EditorBrowsableState.Advanced)>
    <DataContractAttribute()>
    Partial Public Class DeleteToDoResponseBody

        Public Sub New()
        End Sub
    End Class

    <CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")>
    Public Interface IService1Channel
        Inherits IService1, ServiceModel.IClientChannel
    End Interface

    <DebuggerStepThroughAttribute()>
    <CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")>
    Partial Public Class Service1Client
        Inherits ServiceModel.ClientBase(Of IService1)
        Implements IService1

        ''' <summary>
        ''' Implement this partial method to configure the service endpoint.
        ''' </summary>
        ''' <paramname="serviceEndpoint">The endpoint to configure</param>
        ''' <paramname="clientCredentials">The client credentials</param>
        Partial Private Shared Sub ConfigureEndpoint(ByVal serviceEndpoint As ServiceModel.Description.ServiceEndpoint, ByVal clientCredentials As ServiceModel.Description.ClientCredentials)
        End Sub

        Public Sub New(ByVal endpointConfiguration As EndpointConfiguration)
            MyBase.New(GetBindingForEndpoint(endpointConfiguration), GetEndpointAddress(endpointConfiguration))
            Endpoint.Name = endpointConfiguration.ToString()
            ConfigureEndpoint(Endpoint, ClientCredentials)
        End Sub

        Public Sub New(ByVal endpointConfiguration As EndpointConfiguration, ByVal remoteAddress As String)
            MyBase.New(GetBindingForEndpoint(endpointConfiguration), New ServiceModel.EndpointAddress(remoteAddress))
            Endpoint.Name = endpointConfiguration.ToString()
            ConfigureEndpoint(Endpoint, ClientCredentials)
        End Sub

        Public Sub New(ByVal endpointConfiguration As EndpointConfiguration, ByVal remoteAddress As ServiceModel.EndpointAddress)
            MyBase.New(GetBindingForEndpoint(endpointConfiguration), remoteAddress)
            Endpoint.Name = endpointConfiguration.ToString()
            ConfigureEndpoint(Endpoint, ClientCredentials)
        End Sub

        Public Sub New(ByVal binding As ServiceModel.Channels.Binding, ByVal remoteAddress As ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub

        <ComponentModel.EditorBrowsableAttribute(ComponentModel.EditorBrowsableState.Advanced)>
        Private Function GetToDosAsync1(ByVal request As GetToDosRequest) As Task(Of GetToDosResponse) Implements IService1.GetToDosAsync
            Return Channel.GetToDosAsync(request)
        End Function

        Public Function GetToDosAsync(ByVal ownerId As String) As Task(Of GetToDosResponse)
            Dim inValue As GetToDosRequest = New GetToDosRequest()
            inValue.Body = New GetToDosRequestBody()
            inValue.Body.ownerId = ownerId
            Return CType(Me, IService1).GetToDosAsync(inValue)
        End Function

        <ComponentModel.EditorBrowsableAttribute(ComponentModel.EditorBrowsableState.Advanced)>
        Private Function AddOrUpdateToDoAsync1(ByVal request As AddOrUpdateToDoRequest) As Task(Of AddOrUpdateToDoResponse) Implements IService1.AddOrUpdateToDoAsync
            Return Channel.AddOrUpdateToDoAsync(request)
        End Function

        Public Function AddOrUpdateToDoAsync(ByVal toDoItem As ToDoItem) As Task(Of AddOrUpdateToDoResponse)
            Dim inValue As AddOrUpdateToDoRequest = New AddOrUpdateToDoRequest()
            inValue.Body = New AddOrUpdateToDoRequestBody()
            inValue.Body.toDoItem = toDoItem
            Return CType(Me, IService1).AddOrUpdateToDoAsync(inValue)
        End Function

        <ComponentModel.EditorBrowsableAttribute(ComponentModel.EditorBrowsableState.Advanced)>
        Private Function DeleteToDoAsync1(ByVal request As DeleteToDoRequest) As Task(Of DeleteToDoResponse) Implements IService1.DeleteToDoAsync
            Return Channel.DeleteToDoAsync(request)
        End Function

        Public Function DeleteToDoAsync(ByVal toDoItem As ToDoItem) As Task(Of DeleteToDoResponse)
            Dim inValue As DeleteToDoRequest = New DeleteToDoRequest()
            inValue.Body = New DeleteToDoRequestBody()
            inValue.Body.toDoItem = toDoItem
            Return CType(Me, IService1).DeleteToDoAsync(inValue)
        End Function

        Public Overridable Function OpenAsync() As Task
            Return Task.Factory.FromAsync(CType(Me, ServiceModel.ICommunicationObject).BeginOpen(Nothing, Nothing), New Action(Of IAsyncResult)(AddressOf CType(Me, ServiceModel.ICommunicationObject).EndOpen))
        End Function

        Public Overridable Function CloseAsync() As Task
            Return Task.Factory.FromAsync(CType(Me, ServiceModel.ICommunicationObject).BeginClose(Nothing, Nothing), New Action(Of IAsyncResult)(AddressOf CType(Me, ServiceModel.ICommunicationObject).EndClose))
        End Function

        Private Shared Function GetBindingForEndpoint(ByVal endpointConfiguration As EndpointConfiguration) As ServiceModel.Channels.Binding
            If endpointConfiguration = EndpointConfiguration.BasicHttpBinding_IService1 Then
#If OPENSILVER Then
                Return New ServiceModel.Channels.CustomBinding()
#End If
                Dim result As ServiceModel.BasicHttpBinding = New ServiceModel.BasicHttpBinding()
                result.MaxBufferSize = Integer.MaxValue
                result.ReaderQuotas = Xml.XmlDictionaryReaderQuotas.Max
                result.MaxReceivedMessageSize = Integer.MaxValue
                result.AllowCookies = True
                Return result
            End If
            If endpointConfiguration = EndpointConfiguration.BasicHttpsBinding_IService1 Then
                Dim result As ServiceModel.BasicHttpBinding = New ServiceModel.BasicHttpBinding()
                result.MaxBufferSize = Integer.MaxValue
                result.ReaderQuotas = Xml.XmlDictionaryReaderQuotas.Max
                result.MaxReceivedMessageSize = Integer.MaxValue
                result.AllowCookies = True
                result.Security.Mode = ServiceModel.BasicHttpSecurityMode.Transport
                Return result
            End If
            Throw New InvalidOperationException(String.Format("Could not find endpoint with name '{0}'.", endpointConfiguration))
        End Function

        Private Shared Function GetEndpointAddress(ByVal endpointConfiguration As EndpointConfiguration) As ServiceModel.EndpointAddress
            If endpointConfiguration = EndpointConfiguration.BasicHttpBinding_IService1 Then
                Return New ServiceModel.EndpointAddress("http://cshtml5-soap-sample.azurewebsites.net/Service1.svc")
            End If
            If endpointConfiguration = EndpointConfiguration.BasicHttpsBinding_IService1 Then
                Return New ServiceModel.EndpointAddress("https://cshtml5-soap-sample.azurewebsites.net/Service1.svc")
            End If
            Throw New InvalidOperationException(String.Format("Could not find endpoint with name '{0}'.", endpointConfiguration))
        End Function

        Public Enum EndpointConfiguration

            BasicHttpBinding_IService1

            BasicHttpsBinding_IService1
        End Enum
    End Class
End Namespace
