//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ToDoItem", Namespace="http://tempuri.org/")]
    public partial class ToDoItem : object
    {
        
        private string IdField;
        
        private string OwnerIdField;
        
        private string DescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string OwnerId
        {
            get
            {
                return this.OwnerIdField;
            }
            set
            {
                this.OwnerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetToDos", ReplyAction="http://tempuri.org/IService1/GetToDosResponse")]
        System.Threading.Tasks.Task<ServiceReference1.GetToDosResponse> GetToDosAsync(ServiceReference1.GetToDosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddOrUpdateToDo", ReplyAction="http://tempuri.org/IService1/AddOrUpdateToDoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.AddOrUpdateToDoResponse> AddOrUpdateToDoAsync(ServiceReference1.AddOrUpdateToDoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteToDo", ReplyAction="http://tempuri.org/IService1/DeleteToDoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.DeleteToDoResponse> DeleteToDoAsync(ServiceReference1.DeleteToDoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetToDosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetToDos", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetToDosRequestBody Body;
        
        public GetToDosRequest()
        {
        }
        
        public GetToDosRequest(ServiceReference1.GetToDosRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetToDosRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ownerId;
        
        public GetToDosRequestBody()
        {
        }
        
        public GetToDosRequestBody(string ownerId)
        {
            this.ownerId = ownerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetToDosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetToDosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetToDosResponseBody Body;
        
        public GetToDosResponse()
        {
        }
        
        public GetToDosResponse(ServiceReference1.GetToDosResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetToDosResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.ToDoItem[] GetToDosResult;
        
        public GetToDosResponseBody()
        {
        }
        
        public GetToDosResponseBody(ServiceReference1.ToDoItem[] GetToDosResult)
        {
            this.GetToDosResult = GetToDosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddOrUpdateToDoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddOrUpdateToDo", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.AddOrUpdateToDoRequestBody Body;
        
        public AddOrUpdateToDoRequest()
        {
        }
        
        public AddOrUpdateToDoRequest(ServiceReference1.AddOrUpdateToDoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddOrUpdateToDoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.ToDoItem toDoItem;
        
        public AddOrUpdateToDoRequestBody()
        {
        }
        
        public AddOrUpdateToDoRequestBody(ServiceReference1.ToDoItem toDoItem)
        {
            this.toDoItem = toDoItem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddOrUpdateToDoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddOrUpdateToDoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.AddOrUpdateToDoResponseBody Body;
        
        public AddOrUpdateToDoResponse()
        {
        }
        
        public AddOrUpdateToDoResponse(ServiceReference1.AddOrUpdateToDoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddOrUpdateToDoResponseBody
    {
        
        public AddOrUpdateToDoResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteToDoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteToDo", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.DeleteToDoRequestBody Body;
        
        public DeleteToDoRequest()
        {
        }
        
        public DeleteToDoRequest(ServiceReference1.DeleteToDoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteToDoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.ToDoItem toDoItem;
        
        public DeleteToDoRequestBody()
        {
        }
        
        public DeleteToDoRequestBody(ServiceReference1.ToDoItem toDoItem)
        {
            this.toDoItem = toDoItem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteToDoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteToDoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.DeleteToDoResponseBody Body;
        
        public DeleteToDoResponse()
        {
        }
        
        public DeleteToDoResponse(ServiceReference1.DeleteToDoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteToDoResponseBody
    {
        
        public DeleteToDoResponseBody()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IService1Channel : ServiceReference1.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceReference1.IService1>, ServiceReference1.IService1
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetToDosResponse> ServiceReference1.IService1.GetToDosAsync(ServiceReference1.GetToDosRequest request)
        {
            return base.Channel.GetToDosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetToDosResponse> GetToDosAsync(string ownerId)
        {
            ServiceReference1.GetToDosRequest inValue = new ServiceReference1.GetToDosRequest();
            inValue.Body = new ServiceReference1.GetToDosRequestBody();
            inValue.Body.ownerId = ownerId;
            return ((ServiceReference1.IService1)(this)).GetToDosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.AddOrUpdateToDoResponse> ServiceReference1.IService1.AddOrUpdateToDoAsync(ServiceReference1.AddOrUpdateToDoRequest request)
        {
            return base.Channel.AddOrUpdateToDoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.AddOrUpdateToDoResponse> AddOrUpdateToDoAsync(ServiceReference1.ToDoItem toDoItem)
        {
            ServiceReference1.AddOrUpdateToDoRequest inValue = new ServiceReference1.AddOrUpdateToDoRequest();
            inValue.Body = new ServiceReference1.AddOrUpdateToDoRequestBody();
            inValue.Body.toDoItem = toDoItem;
            return ((ServiceReference1.IService1)(this)).AddOrUpdateToDoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.DeleteToDoResponse> ServiceReference1.IService1.DeleteToDoAsync(ServiceReference1.DeleteToDoRequest request)
        {
            return base.Channel.DeleteToDoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.DeleteToDoResponse> DeleteToDoAsync(ServiceReference1.ToDoItem toDoItem)
        {
            ServiceReference1.DeleteToDoRequest inValue = new ServiceReference1.DeleteToDoRequest();
            inValue.Body = new ServiceReference1.DeleteToDoRequestBody();
            inValue.Body.toDoItem = toDoItem;
            return ((ServiceReference1.IService1)(this)).DeleteToDoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
#if OPENSILVER
                return new System.ServiceModel.Channels.CustomBinding();
#endif
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://cshtml5-soap-sample.azurewebsites.net/Service1.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("https://cshtml5-soap-sample.azurewebsites.net/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
            
            BasicHttpsBinding_IService1,
        }
    }
}
