<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <NoXamlPreprocessor>True</NoXamlPreprocessor>
    <OpenSilverType>7</OpenSilverType>
    <PublishTrimmed>true</PublishTrimmed>
    <WasmEnableSIMD>false</WasmEnableSIMD>
    <OutputPath>bin/$(Configuration)_fs</OutputPath>
    <IntermediateOutputPath>obj/$(Configuration)_fs</IntermediateOutputPath>
    <DefineTrace>true</DefineTrace>
    <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
    <WasmEnableWebcil>false</WasmEnableWebcil>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenSilver.WebAssembly" Version="[$(OpenSilverVersion)]" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.16" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.16" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenSilver.Showcase\OpenSilver.Showcase.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="mscorlib"/>
  </ItemGroup>

</Project>
