<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDefaultItems>false</EnableDefaultItems>
    <DefineSilverlight>true</DefineSilverlight>
  </PropertyGroup>


  <ItemGroup>
    <ProjectReference Include="..\src\OpenSilver.Samples.Showcase.csproj" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="MudBlazor" Version="8.5.1" />
	  <PackageReference Include="OpenSilver.Blazor" Version="3.2.0-preview-1" />
    <PackageReference Include="OpenSilver" Version="[$(OpenSilverVersion)]" />
    <PackageReference Include="OpenSilver.ControlsKit" Version="[$(OpenSilverControlsKitVersion)]" />
  </ItemGroup>


	<ItemGroup>
		<Compile Include="Samples\Button\MudBlazorButton_Demo.xaml.cs" />
		<Compile Include="Samples\ColorPicker\MudBlazorColorpicker_Demo.xaml.cs" />
		<Compile Include="Samples\DataGrid\Employees.cs" />
		<Compile Include="Samples\DataGrid\MudBlazorDataGrid_Demo.xaml.cs" />
		<Compile Include="Samples\MudBlazor_Sample.xaml.cs" />
		<Compile Include="Samples\Snackbar\MudBlazorSnackbar_Demo.xaml.cs" />
	</ItemGroup>

	<ItemGroup>
    <Page Include="Samples\Button\MudBlazorButton_Demo.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Samples\ColorPicker\MudBlazorColorpicker_Demo.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Samples\DataGrid\MudBlazorDataGrid_Demo.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Samples\MudBlazor_Sample.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Samples\Snackbar\MudBlazorSnackbar_Demo.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

</Project>
