<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDefaultItems>false</EnableDefaultItems>
    <DefineSilverlight>true</DefineSilverlight>
    <AssemblyName>OpenSilver.Samples.Showcase.DevExpress2</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Samples\DevExpress_Sample.xaml.cs" />
    <Compile Include="Samples\RichEdit\DevExpressRichEdit_Demo.xaml.cs" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="DevExpress.Blazor.RichEdit" Version="25.1.3" />
	  <PackageReference Include="OpenSilver.Blazor" Version="3.3.0-preview-2025-06-27-152003-99e4b398" />
	  <PackageReference Include="OpenSilver" Version="[$(OpenSilverVersion)]" />
	  <PackageReference Include="OpenSilver.ControlsKit" Version="[$(OpenSilverControlsKitVersion)]" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="Samples\DevExpress_Sample.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Samples\RichEdit\DevExpressRichEdit_Demo.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

</Project>
