Imports System.Collections.ObjectModel
Imports System.Windows.Data

Namespace OpenSilver.Samples.Showcase
    Friend Class AtomicElements
        Public Shared Property Elements As PagedCollectionView = New PagedCollectionView(GetListOfElements())

        Private Shared Function GetListOfElements() As ObservableCollection(Of Element)
            Return New ObservableCollection(Of Element)() From {
                New Element("Hydrogen", "H"),
                New Element("Helium", "He"),
                New Element("Lithium", "Li"),
                New Element("Beryllium", "Be"),
                New Element("Boron", "B"),
                New Element("Carbon", "C"),
                New Element("Nitrogen", "N"),
                New Element("Oxygen", "O"),
                New Element("Fluorine", "F"),
                New Element("Neon", "Ne"),
                New Element("Sodium", "Na"),
                New Element("Magnesium", "Mg"),
                New Element("Aluminum", "Al"),
                New Element("Silicon", "Si"),
                New Element("Phosphorus", "P"),
                New Element("Sulfur", "S"),
                New Element("Chlorine", "Cl"),
                New Element("Argon", "Ar"),
                New Element("Potassium", "K"),
                New Element("Calcium", "Ca"),
                New Element("Scandium", "Sc"),
                New Element("Titanium", "Ti"),
                New Element("Vanadium", "V"),
                New Element("Chromium", "Cr"),
                New Element("Manganese", "Mn"),
                New Element("Iron", "Fe"),
                New Element("Cobalt", "Co"),
                New Element("Nickel", "Ni"),
                New Element("Copper", "Cu"),
                New Element("Zinc", "Zn"),
                New Element("Gallium", "Ga"),
                New Element("Germanium", "Ge"),
                New Element("Arsenic", "As"),
                New Element("Selenium", "Se"),
                New Element("Bromine", "Br"),
                New Element("Krypton", "Kr"),
                New Element("Rubidium", "Rb"),
                New Element("Strontium", "Sr"),
                New Element("Yttrium", "Y"),
                New Element("Zirconium", "Zr"),
                New Element("Niobium", "Nb"),
                New Element("Molybdenum", "Mo"),
                New Element("Technetium", "Tc"),
                New Element("Ruthenium", "Ru"),
                New Element("Rhodium", "Rh"),
                New Element("Palladium", "Pd"),
                New Element("Silver", "Ag"),
                New Element("Cadmium", "Cd"),
                New Element("Indium", "In"),
                New Element("Tin", "Sn"),
                New Element("Antimony", "Sb"),
                New Element("Tellurium", "Te"),
                New Element("Iodine", "I"),
                New Element("Xenon", "Xe"),
                New Element("Cesium", "Cs"),
                New Element("Barium", "Ba"),
                New Element("Lanthanum", "La"),
                New Element("Cerium", "Ce"),
                New Element("Praseodymium", "Pr"),
                New Element("Neodymium", "Nd"),
                New Element("Promethium", "Pm"),
                New Element("Samarium", "Sm"),
                New Element("Europium", "Eu"),
                New Element("Gadolinium", "Gd"),
                New Element("Terbium", "Tb"),
                New Element("Dysprosium", "Dy"),
                New Element("Holmium", "Ho"),
                New Element("Erbium", "Er"),
                New Element("Thulium", "Tm"),
                New Element("Ytterbium", "Yb"),
                New Element("Lutetium", "Lu"),
                New Element("Hafnium", "Hf"),
                New Element("Tantalum", "Ta"),
                New Element("Tungsten", "W"),
                New Element("Rhenium", "Re"),
                New Element("Osmium", "Os"),
                New Element("Iridium", "Ir"),
                New Element("Platinum", "Pt"),
                New Element("Gold", "Au"),
                New Element("Mercury", "Hg"),
                New Element("Thallium", "Tl"),
                New Element("Lead", "Pb"),
                New Element("Bismuth", "Bi"),
                New Element("Polonium", "Po"),
                New Element("Astatine", "At"),
                New Element("Radon", "Rn"),
                New Element("Francium", "Fr"),
                New Element("Radium", "Ra"),
                New Element("Actinium", "Ac"),
                New Element("Thorium", "Th"),
                New Element("Protactinium", "Pa"),
                New Element("Uranium", "U"),
                New Element("Neptunium", "Np"),
                New Element("Plutonium", "Pu"),
                New Element("Americium", "Am"),
                New Element("Curium", "Cm"),
                New Element("Berkelium", "Bk"),
                New Element("Californium", "Cf"),
                New Element("Einsteinium", "Es"),
                New Element("Fermium", "Fm"),
                New Element("Mendelevium", "Md"),
                New Element("Nobelium", "No"),
                New Element("Lawrencium", "Lr"),
                New Element("Rutherfordium", "Rf"),
                New Element("Dubnium", "Db"),
                New Element("Seaborgium", "Sg"),
                New Element("Bohrium", "Bh"),
                New Element("Hassium", "Hs"),
                New Element("Meitnerium", "Mt"),
                New Element("Darmstadtium", "Ds"),
                New Element("Roentgenium", "Rg"),
                New Element("Copernicium", "Cn"),
                New Element("Nihonium", "Nh"),
                New Element("Flerovium", "Fl"),
                New Element("Moscovium", "Mc"),
                New Element("Livermorium", "Lv"),
                New Element("Tennessine", "Ts"),
                New Element("Oganesson", "Og")
            }
        End Function
    End Class

    Class Element
        Public ReadOnly Property Name As String
        Public ReadOnly Property Symbol As String

        Public Sub New(ByVal namevalue As String, ByVal symbolvalue As String)
            Name = namevalue
            Symbol = symbolvalue
        End Sub
    End Class
End Namespace
