//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSHTML5.Samples.Showcase.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ToDoItem", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ToDoItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        private System.Guid OwnerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid OwnerId {
            get {
                return this.OwnerIdField;
            }
            set {
                if ((this.OwnerIdField.Equals(value) != true)) {
                    this.OwnerIdField = value;
                    this.RaisePropertyChanged("OwnerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        // CODEGEN: Generating message contract since element name GetToDosResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetToDos", ReplyAction="http://tempuri.org/IService1/GetToDosResponse")]
        CSHTML5.Samples.Showcase.ServiceReference1.GetToDosResponse GetToDos(CSHTML5.Samples.Showcase.ServiceReference1.GetToDosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetToDos", ReplyAction="http://tempuri.org/IService1/GetToDosResponse")]
        System.Threading.Tasks.Task<CSHTML5.Samples.Showcase.ServiceReference1.GetToDosResponse> GetToDosAsync(CSHTML5.Samples.Showcase.ServiceReference1.GetToDosRequest request);
        
        // CODEGEN: Generating message contract since element name toDoItem from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddOrUpdateToDo", ReplyAction="http://tempuri.org/IService1/AddOrUpdateToDoResponse")]
        CSHTML5.Samples.Showcase.ServiceReference1.AddOrUpdateToDoResponse AddOrUpdateToDo(CSHTML5.Samples.Showcase.ServiceReference1.AddOrUpdateToDoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddOrUpdateToDo", ReplyAction="http://tempuri.org/IService1/AddOrUpdateToDoResponse")]
        System.Threading.Tasks.Task<CSHTML5.Samples.Showcase.ServiceReference1.AddOrUpdateToDoResponse> AddOrUpdateToDoAsync(CSHTML5.Samples.Showcase.ServiceReference1.AddOrUpdateToDoRequest request);
        
        // CODEGEN: Generating message contract since element name toDoItem from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteToDo", ReplyAction="http://tempuri.org/IService1/DeleteToDoResponse")]
        CSHTML5.Samples.Showcase.ServiceReference1.DeleteToDoResponse DeleteToDo(CSHTML5.Samples.Showcase.ServiceReference1.DeleteToDoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteToDo", ReplyAction="http://tempuri.org/IService1/DeleteToDoResponse")]
        System.Threading.Tasks.Task<CSHTML5.Samples.Showcase.ServiceReference1.DeleteToDoResponse> DeleteToDoAsync(CSHTML5.Samples.Showcase.ServiceReference1.DeleteToDoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetToDosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetToDos", Namespace="http://tempuri.org/", Order=0)]
        public CSHTML5.Samples.Showcase.ServiceReference1.GetToDosRequestBody Body;
        
        public GetToDosRequest() {
        }
        
        public GetToDosRequest(CSHTML5.Samples.Showcase.ServiceReference1.GetToDosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetToDosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid ownerId;
        
        public GetToDosRequestBody() {
        }
        
        public GetToDosRequestBody(System.Guid ownerId) {
            this.ownerId = ownerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetToDosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetToDosResponse", Namespace="http://tempuri.org/", Order=0)]
        public CSHTML5.Samples.Showcase.ServiceReference1.GetToDosResponseBody Body;
        
        public GetToDosResponse() {
        }
        
        public GetToDosResponse(CSHTML5.Samples.Showcase.ServiceReference1.GetToDosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetToDosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CSHTML5.Samples.Showcase.ServiceReference1.ToDoItem[] GetToDosResult;
        
        public GetToDosResponseBody() {
        }
        
        public GetToDosResponseBody(CSHTML5.Samples.Showcase.ServiceReference1.ToDoItem[] GetToDosResult) {
            this.GetToDosResult = GetToDosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddOrUpdateToDoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddOrUpdateToDo", Namespace="http://tempuri.org/", Order=0)]
        public CSHTML5.Samples.Showcase.ServiceReference1.AddOrUpdateToDoRequestBody Body;
        
        public AddOrUpdateToDoRequest() {
        }
        
        public AddOrUpdateToDoRequest(CSHTML5.Samples.Showcase.ServiceReference1.AddOrUpdateToDoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddOrUpdateToDoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CSHTML5.Samples.Showcase.ServiceReference1.ToDoItem toDoItem;
        
        public AddOrUpdateToDoRequestBody() {
        }
        
        public AddOrUpdateToDoRequestBody(CSHTML5.Samples.Showcase.ServiceReference1.ToDoItem toDoItem) {
            this.toDoItem = toDoItem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddOrUpdateToDoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddOrUpdateToDoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CSHTML5.Samples.Showcase.ServiceReference1.AddOrUpdateToDoResponseBody Body;
        
        public AddOrUpdateToDoResponse() {
        }
        
        public AddOrUpdateToDoResponse(CSHTML5.Samples.Showcase.ServiceReference1.AddOrUpdateToDoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddOrUpdateToDoResponseBody {
        
        public AddOrUpdateToDoResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteToDoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteToDo", Namespace="http://tempuri.org/", Order=0)]
        public CSHTML5.Samples.Showcase.ServiceReference1.DeleteToDoRequestBody Body;
        
        public DeleteToDoRequest() {
        }
        
        public DeleteToDoRequest(CSHTML5.Samples.Showcase.ServiceReference1.DeleteToDoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteToDoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CSHTML5.Samples.Showcase.ServiceReference1.ToDoItem toDoItem;
        
        public DeleteToDoRequestBody() {
        }
        
        public DeleteToDoRequestBody(CSHTML5.Samples.Showcase.ServiceReference1.ToDoItem toDoItem) {
            this.toDoItem = toDoItem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteToDoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteToDoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CSHTML5.Samples.Showcase.ServiceReference1.DeleteToDoResponseBody Body;
        
        public DeleteToDoResponse() {
        }
        
        public DeleteToDoResponse(CSHTML5.Samples.Showcase.ServiceReference1.DeleteToDoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteToDoResponseBody {
        
        public DeleteToDoResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : CSHTML5.Samples.Showcase.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<CSHTML5.Samples.Showcase.ServiceReference1.IService1>, CSHTML5.Samples.Showcase.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSHTML5.Samples.Showcase.ServiceReference1.GetToDosResponse CSHTML5.Samples.Showcase.ServiceReference1.IService1.GetToDos(CSHTML5.Samples.Showcase.ServiceReference1.GetToDosRequest request) {
            return base.Channel.GetToDos(request);
        }
        
        public CSHTML5.Samples.Showcase.ServiceReference1.ToDoItem[] GetToDos(System.Guid ownerId) {
            CSHTML5.Samples.Showcase.ServiceReference1.GetToDosRequest inValue = new CSHTML5.Samples.Showcase.ServiceReference1.GetToDosRequest();
            inValue.Body = new CSHTML5.Samples.Showcase.ServiceReference1.GetToDosRequestBody();
            inValue.Body.ownerId = ownerId;
            CSHTML5.Samples.Showcase.ServiceReference1.GetToDosResponse retVal = ((CSHTML5.Samples.Showcase.ServiceReference1.IService1)(this)).GetToDos(inValue);
            return retVal.Body.GetToDosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSHTML5.Samples.Showcase.ServiceReference1.GetToDosResponse> CSHTML5.Samples.Showcase.ServiceReference1.IService1.GetToDosAsync(CSHTML5.Samples.Showcase.ServiceReference1.GetToDosRequest request) {
            return base.Channel.GetToDosAsync(request);
        }
        
        public System.Threading.Tasks.Task<CSHTML5.Samples.Showcase.ServiceReference1.GetToDosResponse> GetToDosAsync(System.Guid ownerId) {
            CSHTML5.Samples.Showcase.ServiceReference1.GetToDosRequest inValue = new CSHTML5.Samples.Showcase.ServiceReference1.GetToDosRequest();
            inValue.Body = new CSHTML5.Samples.Showcase.ServiceReference1.GetToDosRequestBody();
            inValue.Body.ownerId = ownerId;
            return ((CSHTML5.Samples.Showcase.ServiceReference1.IService1)(this)).GetToDosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSHTML5.Samples.Showcase.ServiceReference1.AddOrUpdateToDoResponse CSHTML5.Samples.Showcase.ServiceReference1.IService1.AddOrUpdateToDo(CSHTML5.Samples.Showcase.ServiceReference1.AddOrUpdateToDoRequest request) {
            return base.Channel.AddOrUpdateToDo(request);
        }
        
        public void AddOrUpdateToDo(CSHTML5.Samples.Showcase.ServiceReference1.ToDoItem toDoItem) {
            CSHTML5.Samples.Showcase.ServiceReference1.AddOrUpdateToDoRequest inValue = new CSHTML5.Samples.Showcase.ServiceReference1.AddOrUpdateToDoRequest();
            inValue.Body = new CSHTML5.Samples.Showcase.ServiceReference1.AddOrUpdateToDoRequestBody();
            inValue.Body.toDoItem = toDoItem;
            CSHTML5.Samples.Showcase.ServiceReference1.AddOrUpdateToDoResponse retVal = ((CSHTML5.Samples.Showcase.ServiceReference1.IService1)(this)).AddOrUpdateToDo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSHTML5.Samples.Showcase.ServiceReference1.AddOrUpdateToDoResponse> CSHTML5.Samples.Showcase.ServiceReference1.IService1.AddOrUpdateToDoAsync(CSHTML5.Samples.Showcase.ServiceReference1.AddOrUpdateToDoRequest request) {
            return base.Channel.AddOrUpdateToDoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CSHTML5.Samples.Showcase.ServiceReference1.AddOrUpdateToDoResponse> AddOrUpdateToDoAsync(CSHTML5.Samples.Showcase.ServiceReference1.ToDoItem toDoItem) {
            CSHTML5.Samples.Showcase.ServiceReference1.AddOrUpdateToDoRequest inValue = new CSHTML5.Samples.Showcase.ServiceReference1.AddOrUpdateToDoRequest();
            inValue.Body = new CSHTML5.Samples.Showcase.ServiceReference1.AddOrUpdateToDoRequestBody();
            inValue.Body.toDoItem = toDoItem;
            return ((CSHTML5.Samples.Showcase.ServiceReference1.IService1)(this)).AddOrUpdateToDoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSHTML5.Samples.Showcase.ServiceReference1.DeleteToDoResponse CSHTML5.Samples.Showcase.ServiceReference1.IService1.DeleteToDo(CSHTML5.Samples.Showcase.ServiceReference1.DeleteToDoRequest request) {
            return base.Channel.DeleteToDo(request);
        }
        
        public void DeleteToDo(CSHTML5.Samples.Showcase.ServiceReference1.ToDoItem toDoItem) {
            CSHTML5.Samples.Showcase.ServiceReference1.DeleteToDoRequest inValue = new CSHTML5.Samples.Showcase.ServiceReference1.DeleteToDoRequest();
            inValue.Body = new CSHTML5.Samples.Showcase.ServiceReference1.DeleteToDoRequestBody();
            inValue.Body.toDoItem = toDoItem;
            CSHTML5.Samples.Showcase.ServiceReference1.DeleteToDoResponse retVal = ((CSHTML5.Samples.Showcase.ServiceReference1.IService1)(this)).DeleteToDo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSHTML5.Samples.Showcase.ServiceReference1.DeleteToDoResponse> CSHTML5.Samples.Showcase.ServiceReference1.IService1.DeleteToDoAsync(CSHTML5.Samples.Showcase.ServiceReference1.DeleteToDoRequest request) {
            return base.Channel.DeleteToDoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CSHTML5.Samples.Showcase.ServiceReference1.DeleteToDoResponse> DeleteToDoAsync(CSHTML5.Samples.Showcase.ServiceReference1.ToDoItem toDoItem) {
            CSHTML5.Samples.Showcase.ServiceReference1.DeleteToDoRequest inValue = new CSHTML5.Samples.Showcase.ServiceReference1.DeleteToDoRequest();
            inValue.Body = new CSHTML5.Samples.Showcase.ServiceReference1.DeleteToDoRequestBody();
            inValue.Body.toDoItem = toDoItem;
            return ((CSHTML5.Samples.Showcase.ServiceReference1.IService1)(this)).DeleteToDoAsync(inValue);
        }
    }
}
